name: C/C++ CI

on: 
   push:
      paths:
         - '**.cpp'
jobs:
   build:

     runs-on: macOS-latest
     steps:
     - name: checkout repo
       uses: actions/checkout@v1
     - name: make
       run: make -k
