name: C/C++ CI

on: 
   push:
            paths:
               - '**.cpp'
            branches:
               - master
jobs:
   build:

     runs-on: ubuntu-latest
     steps:
     - name: checkout repo
       uses: actions/checkout@v1
     - name: make
       run: make -k
